1.perform inner join

In [7]:
import pandas as pd 

df=pd.read_csv(r'C:\Desktop\luminar\Eda1\pandas1\files\custom_windows.csv')
df1=pd.read_csv(r'C:\Desktop\luminar\Eda1\pandas1\files\order_windows.csv')

In [10]:
df2=pd.merge(df,df1,on='id',how='inner')

2.salary above 2k

In [12]:
salry_abve2=pd.merge(df,df1,on='id',how='inner')[df2['salary']>2000]
print(salry_abve2)

   id    name  age location  salary  oid                  dat  amount
3   4  Monika   25   Mumbai    6500  103  2015-05-20 00:00:00    2060

3.latst date purchase date , name ,age, loc,amount,date

In [18]:
pd.merge(df,df1,on='id',how='inner').sort_values('dat').head(1)[['name','age','location','dat']]

     name  age location                  dat
3  Monika   25   Mumbai  2015-05-20 00:00:00

4.age  minimum 1 emp name , age , dat,amount

In [20]:
pd.merge(df,df1,on='id',how='inner').sort_values('age').head(1)[['name','age','dat','amount']]

       name  age                  dat  amount
1  Chandler   23  2016-10-08 00:00:00    3000

5.each location count

In [21]:
pd.merge(df,df1,on='id',how='inner').groupby('location')['location'].count()

location
Delhi     1
Kota      2
Mumbai    1
Name: location, dtype: int64