In [1]:
import pandas as pd 

df=pd.read_csv(r"C:\Desktop\luminar\Eda1\pandas1\files\customer1.csv")

# 1.find total number of missing Values

In [4]:
mising_value=df.isna().sum()
print(mising_value)

id       0
fname    0
lname    0
age      0
prof     0
loc      1
dtype: int64

# 2. fill thr misisng values using imdia

In [8]:
df1 =df.fillna('india')
print(df1.isna().sum())

id       0
fname    0
lname    0
age      0
prof     0
loc      0
dtype: int64

# 3. india work fname,lname,age,prof

In [9]:
df1[df['loc']=='india'][['fname','lname','age','prof']]

       fname       lname  age                         prof
0   Kristina       Chung   55                        Pilot
7      Hazel      Bender   63                    Carpenter
8    Malcolm      Wagner   39                       Artist
9    Dolores  McLaughlin   60                       Writer
10   Francis    McNamara   47                    Therapist
11     Sandy      Raynor   26                       Writer
12    Marion        Moon   41                    Carpenter
13      Beth     Woodard   65                     Musician
14     Julia       Desai   49                     Musician
15    Jerome     Wallace   52                   Pharmacist
16      Neal    Lawrence   72  Computer support specialist
17      Jean     Griffin   45             Childcare worker
18  Kristine   Dougherty   63            Financial analyst
19   Crystal      Powers   67       Engineering technician
20      Alex         May   39      Environmental scientist
21      Eric      Steele   66                       Doctor
22    Wesley      Teague   42                    Carpenter
23  Franklin        Vick   28                       Dancer
24    Claire   Gallagher   42                     Musician
25    Marian     Solomon   27                       Lawyer
26    Marcia       Walsh   64                   Accountant

# 4.age macm 5 fname,lname,age,prof

In [12]:
df1.sort_values(by='age',ascending=False)[['fname','lname','age']].head(5)

        fname    lname  age
324      Ruth   Harmon   75
88     Sherri   Sutton   75
274  Lawrence    Miles   74
241      Edna    Hoyle   74
258  Margaret  Burgess   74

#5. Age minimum 3 emp fname, Lname, age

In [11]:
df1.sort_values(by='age')[['fname','lname','age']].head(3)

       fname    lname  age
51   Shirley  Merritt   21
348  Russell   Dalton   21
291    Donna     Rice   21

#6. india work, age mxm 1 emp fame, Loame, age, prof

In [13]:
df1[df1['loc']=='india'].sort_values(by='age',ascending=False)[['fname','lname','age']].head(1)

   fname     lname  age
16  Neal  Lawrence   72

#7. Pilot prof, age mxm 3 emp fname, Lname, age

In [15]:
df1[df1['prof']=='Pilot'].sort_values(by='age',ascending=False)[['fname','lname','age']].head(3)

    fname     lname  age
391  Emma     Olson   74
402   Leo  Lassiter   65
228  Faye    Norman   64

#8. india work and prof Doctor, age minimum 1 emp fname, Lname

In [21]:
df1[(df1['loc']=='india')&(df1['prof']=='Doctor')].sort_values(by='age',ascending=False)[['fname','lname','age']].head(1)

   fname   lname  age
21  Eric  Steele   66

#9. uk work age minimum 5 emp fane, Lname, age

In [24]:
df1[df1['loc']=='uk'].sort_values(by='age',ascending=True)[['fname','lname','age']].head(5)

       fname      lname  age
51   Shirley    Merritt   21
53    Judith     Cooper   22
31  Gretchen  Goldstein   24
34   Shelley      Weeks   25
36     Elsie     Barton   27

#10. uk work and age below 30 foame, Iname, age

In [25]:
df1[(df1['loc']=='uk')&(df1['age']<30)].sort_values(by='age',ascending=True)[['fname','lname','age']].head(5)

       fname      lname  age
51   Shirley    Merritt   21
53    Judith     Cooper   22
31  Gretchen  Goldstein   24
34   Shelley      Weeks   25
39   Douglas       Ross   27