In [365]:
import pandas as pd
import seaborn as sns

# B1 floor

In [366]:
b1 = pd.read_csv("/content/b1.csv",comment="#")
b1

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,267,NaN,NaN,...,1,2412,-68.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0
267,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,268,NaN,NaN,...,64,5320,-82.0,NaN,NaN,IEEE80211AX,NaN,MHZ_160,55035d5186107949,8270.0
268,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,269,NaN,NaN,...,1,2412,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0
269,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,270,NaN,NaN,...,1,2412,-90.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0
270,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,271,NaN,NaN,...,64,5320,-82.0,NaN,NaN,IEEE80211AX,NaN,MHZ_160,55035d5186107949,8270.0

In [367]:
b1.columns

Index(['deviceTime', 'latitude', 'longitude', 'altitude', 'speed', 'accuracy',
       'missionId', 'recordNumber', 'sourceAddress', 'destinationAddress',
       'bssid', 'beaconInterval', 'serviceSetType', 'ssid', 'supportedRates',
       'extendedSupportedRates', 'cipherSuites', 'akmSuites', 'encryptionType',
       'wps', 'channel', 'frequencyMhz', 'signalStrength', 'snr', 'nodeType',
       'standard', 'passpoint', 'bandwidth', 'deviceSerialNumber',
       'locationAge'],
      dtype='object')

In [368]:
b1['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2',
       'Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', nan, 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra'],
      dtype=object)

In [369]:
b1 = b1[~b1['ssid'].isin(['Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', 'Y-5', 'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra'])]
b1['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2', nan],
      dtype=object)

In [370]:
b1 = b1.dropna(subset=['ssid'])
b1['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2'], dtype=object)

In [371]:
b1.isna().sum()

deviceTime                  0
latitude                    0
longitude                   0
altitude                    0
speed                       0
accuracy                    0
missionId                   0
recordNumber                0
sourceAddress             239
destinationAddress        239
bssid                       0
beaconInterval            239
serviceSetType            239
ssid                        0
supportedRates            239
extendedSupportedRates    239
cipherSuites              239
akmSuites                 239
encryptionType              0
wps                         0
channel                     0
frequencyMhz                0
signalStrength              0
snr                       239
nodeType                  239
standard                    0
passpoint                 239
bandwidth                   0
deviceSerialNumber          0
locationAge                 9
dtype: int64

In [372]:
b1

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,265,NaN,NaN,...,1,2412,-86.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0
265,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,266,NaN,NaN,...,1,2412,-59.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0
266,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,267,NaN,NaN,...,1,2412,-68.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0
268,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,269,NaN,NaN,...,1,2412,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0
269,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,-58.4,0,100,NS 55035d5186107949 20261015-115404,270,NaN,NaN,...,1,2412,-90.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8270.0

In [373]:
b1.drop(['altitude', 'speed', 'accuracy',
       'missionId', 'recordNumber', 'sourceAddress', 'destinationAddress', 'beaconInterval', 'serviceSetType', 'supportedRates',
       'extendedSupportedRates', 'cipherSuites', 'akmSuites', 'encryptionType',
       'wps', 'channel', 'snr', 'nodeType',
       'standard', 'passpoint', 'bandwidth', 'deviceSerialNumber',
       'locationAge'],axis=1,inplace=True)

In [374]:
b1.isna().sum()

deviceTime        0
latitude          0
longitude         0
bssid             0
ssid              0
frequencyMhz      0
signalStrength    0
dtype: int64

In [375]:
b1['floor'] = 'B1'

In [376]:
b1.drop('ssid',axis=1,inplace=True)

In [377]:
b1.dtypes

deviceTime         object
latitude          float64
longitude         float64
bssid              object
frequencyMhz        int64
signalStrength    float64
floor              object
dtype: object

In [378]:



# Create one fingerprint per scan timestamp
wifi_features = b1.pivot_table(
    index="deviceTime",
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)

# Access point not detected = -110 dBm
wifi_features = wifi_features.fillna(-110)

wifi_features = wifi_features.reset_index()
wifi_features['floor'] = 'B1'
wifi_features.to_csv(
    "b1 clean.csv",
    index=False
)

print(wifi_features.head())
print(wifi_features.shape)

bssid                        deviceTime  00:e6:3a:48:24:80  00:e6:3a:48:24:81  \
0      2026-10-15T11:54:11.158612+05:30             -110.0             -110.0
1      2026-10-15T11:54:20.874275+05:30             -110.0             -110.0
2      2026-10-15T11:54:27.671455+05:30             -110.0             -110.0
3      2026-10-15T11:54:33.373453+05:30             -110.0             -110.0
4       2026-10-15T11:54:40.86848+05:30             -110.0             -110.0

bssid  00:e6:3a:5b:77:40  00:e6:3a:5b:77:41  2c:ab:46:7a:b2:e0  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0              -73.0

bssid  2c:ab:46:7a:b2:e1  2c:ab:46:7a:fd:10  2c:ab:46:7a:fd:11  \
0                 -110.0              -76.0              -76.0
1                 -110.0              -81.0              -81.0
2                 -110.0              -80.0              -78.0
3                 -110.0              -79.0              -77.0
4                  -73.0              -77.0              -77.0

bssid  2c:ab:46:7b:10:00  ...  2c:ab:46:ba:fd:11  2c:ab:46:bb:10:00  \
0                  -83.0  ...             -110.0             -110.0
1                  -84.0  ...             -110.0             -110.0
2                  -79.0  ...             -110.0             -110.0
3                  -85.0  ...             -110.0             -110.0
4                  -84.0  ...             -110.0             -110.0

bssid  2c:ab:46:bb:10:01  80:f0:cf:48:1b:e1  9c:a2:f4:87:4c:26  \
0                 -110.0              -93.0              -90.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0              -95.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0              -92.0

bssid  9c:a2:f4:fe:81:1e  c0:c7:0a:72:5a:20  c0:c7:0a:72:5a:21  \
0                  -91.0             -110.0             -110.0
1                  -91.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                  -93.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:4c:1c:70  floor
0                 -110.0     B1
1                 -110.0     B1
2                 -110.0     B1
3                 -110.0     B1
4                 -110.0     B1

[5 rows x 28 columns]
(29, 28)

In [379]:
b1

,deviceTime,latitude,longitude,bssid,frequencyMhz,signalStrength,floor
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,9c:a2:f4:fe:81:1e,2437,-91.0,B1
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,2c:ab:46:7b:5c:f0,2437,-88.0,B1
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,2c:ab:46:7b:5c:f1,2437,-89.0,B1
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,2c:ab:46:7a:fd:10,2437,-76.0,B1
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,2c:ab:46:7b:10:00,2437,-83.0,B1
...,...,...,...,...,...,...,...
264,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,2c:ab:46:7b:10:41,2412,-86.0,B1
265,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,2c:ab:46:7a:b2:e1,2412,-59.0,B1
266,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,2c:ab:46:7a:b2:e0,2412,-68.0,B1
268,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,00:e6:3a:48:24:81,2412,-89.0,B1
269,2026-10-15T12:00:27.961725+05:30,10.018262,76.34269,00:e6:3a:48:24:80,2412,-90.0,B1

# ground floor

In [380]:
ground  = pd.read_csv('/content/ground flooor.csv',comment='#')
ground

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5596,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,-46.3,0.0,125,NS 55035d5186107949 20261015-115404,5597,NaN,NaN,...,161,5805,-84.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,7256.0
5597,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,-46.3,0.0,125,NS 55035d5186107949 20261015-115404,5598,NaN,NaN,...,161,5805,-84.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,7256.0
5598,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,-46.3,0.0,125,NS 55035d5186107949 20261015-115404,5599,NaN,NaN,...,1,2412,-78.0,NaN,NaN,IEEE80211AX,NaN,MHZ_20,55035d5186107949,7256.0
5599,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,-46.3,0.0,125,NS 55035d5186107949 20261015-115404,5600,NaN,NaN,...,10,2457,-87.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,7256.0
5600,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,-46.3,0.0,125,NS 55035d5186107949 20261015-115404,5601,NaN,NaN,...,48,5240,-47.0,NaN,NaN,IEEE80211AX,NaN,MHZ_80,55035d5186107949,7256.0

In [381]:
ground.shape

(5601, 30)

In [382]:
ground.columns

Index(['deviceTime', 'latitude', 'longitude', 'altitude', 'speed', 'accuracy',
       'missionId', 'recordNumber', 'sourceAddress', 'destinationAddress',
       'bssid', 'beaconInterval', 'serviceSetType', 'ssid', 'supportedRates',
       'extendedSupportedRates', 'cipherSuites', 'akmSuites', 'encryptionType',
       'wps', 'channel', 'frequencyMhz', 'signalStrength', 'snr', 'nodeType',
       'standard', 'passpoint', 'bandwidth', 'deviceSerialNumber',
       'locationAge'],
      dtype='object')

In [383]:
ground['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2',
       'Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', nan, 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G',
       'Airtel_Sangeeth menon', 'ichc@2018',
       'TATA Intra_CC:B8:5E:D9:0C:4E', 'JioFiber-ZO3g7',
       'DIRECT-DYDESKTOP-1TKQAN2msET', 'GNXS-2.4G-4D4E62', 'iQOO Z9s 5G',
       'ichc@2018_5GHz', 'MeghaazzZ', 'Luminar_C2-2', 'home',
       'Realme 8 5G', 'IT Plus', 'Galaxy S25 Ultra DA80', '8D_4g',
       'PPC-dd4a', 'OPPO A5 5G y4c9', 'friends hostel gents 1st 5g',
       'friends hostel gents1st 4g', 'BSNL2997420', 'AP_2353236294',
       'The Dance Block', 'OnePlus Nord CE5 c63m', 'Airtel_name_5755',
       'Kiran_5G', 'KFI-Kerala-Govt-free-WiFi', 'iPhone',
       'Orange Technologies'], dtype=object)

In [384]:
ground = ground[~ground['ssid'].isin(['Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149','Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G',
       'Airtel_Sangeeth menon', 'ichc@2018',
       'TATA Intra_CC:B8:5E:D9:0C:4E', 'JioFiber-ZO3g7',
       'DIRECT-DYDESKTOP-1TKQAN2msET', 'GNXS-2.4G-4D4E62', 'iQOO Z9s 5G',
       'ichc@2018_5GHz', 'MeghaazzZ', 'Luminar_C2-2', 'home',
       'Realme 8 5G', 'IT Plus', 'Galaxy S25 Ultra DA80', '8D_4g',
       'PPC-dd4a', 'OPPO A5 5G y4c9', 'friends hostel gents 1st 5g',
       'friends hostel gents1st 4g', 'BSNL2997420', 'AP_2353236294',
       'The Dance Block', 'OnePlus Nord CE5 c63m', 'Airtel_name_5755',
       'Kiran_5G', 'KFI-Kerala-Govt-free-WiFi', 'iPhone',
       'Orange Technologies'])]
ground['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2', nan],
      dtype=object)

In [385]:
ground = ground.dropna(subset=['ssid'])
ground['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2'], dtype=object)

In [386]:
ground.drop(['altitude', 'speed', 'accuracy',
       'missionId', 'recordNumber', 'sourceAddress', 'destinationAddress', 'beaconInterval', 'serviceSetType', 'supportedRates',
       'extendedSupportedRates', 'cipherSuites', 'akmSuites', 'encryptionType',
       'wps', 'channel', 'snr', 'nodeType',
       'standard', 'passpoint', 'bandwidth', 'deviceSerialNumber',
       'locationAge'],axis=1,inplace=True)

In [387]:
ground.isna().sum()

deviceTime        0
latitude          0
longitude         0
bssid             0
ssid              0
frequencyMhz      0
signalStrength    0
dtype: int64

In [388]:
ground.drop('ssid',axis=1,inplace=True)

In [389]:
ground

,deviceTime,latitude,longitude,bssid,frequencyMhz,signalStrength
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,9c:a2:f4:fe:81:1e,2437,-91.0
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,2c:ab:46:7b:5c:f0,2437,-88.0
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,2c:ab:46:7b:5c:f1,2437,-89.0
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,2c:ab:46:7a:fd:10,2437,-76.0
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,2c:ab:46:7b:10:00,2437,-83.0
...,...,...,...,...,...,...
5590,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,80:f0:cf:48:1b:e0,2412,-79.0
5591,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,c0:c7:0a:b2:59:f1,5560,-92.0
5593,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,c0:c7:0a:b3:55:20,5280,-88.0
5596,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,c0:c7:0a:ad:a0:01,5805,-84.0
5597,2026-10-15T12:39:25.030612+05:30,10.018412,76.342671,c0:c7:0a:ad:a0:00,5805,-84.0

In [390]:
wifi_features = ground.pivot_table(
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)
wifi_features

bssid,00:e6:3a:48:24:80,00:e6:3a:48:24:81,00:e6:3a:5b:77:40,00:e6:3a:5b:77:41,00:e6:3a:5d:0f:c0,00:e6:3a:5d:0f:c1,00:e6:3a:5d:13:00,00:e6:3a:5d:13:01,00:e6:3a:88:24:80,00:e6:3a:88:24:81,...,c0:c7:0a:b2:5a:20,c0:c7:0a:b2:5a:21,c0:c7:0a:b2:7d:70,c0:c7:0a:b2:7d:71,c0:c7:0a:b3:55:20,c0:c7:0a:b3:55:21,d0:4f:58:4c:1c:70,d0:4f:58:4c:1c:71,d0:4f:58:8c:1c:70,d0:4f:58:8c:1c:71
signalStrength,-72.361702,-71.272727,-76.190476,-74.921875,-59.3125,-57.580645,-60.916667,-60.333333,-70.704918,-70.783333,...,-67.888889,-67.098039,-62.516129,-61.627119,-79.045455,-76.861111,-64.66,-65.046512,-63.555556,-63.648649

In [391]:
wifi_features1 = b1.pivot_table(
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)
wifi_features1

bssid,00:e6:3a:48:24:80,00:e6:3a:48:24:81,00:e6:3a:5b:77:40,00:e6:3a:5b:77:41,2c:ab:46:7a:b2:e0,2c:ab:46:7a:b2:e1,2c:ab:46:7a:fd:10,2c:ab:46:7a:fd:11,2c:ab:46:7b:10:00,2c:ab:46:7b:10:01,...,2c:ab:46:ba:fd:10,2c:ab:46:ba:fd:11,2c:ab:46:bb:10:00,2c:ab:46:bb:10:01,80:f0:cf:48:1b:e1,9c:a2:f4:87:4c:26,9c:a2:f4:fe:81:1e,c0:c7:0a:72:5a:20,c0:c7:0a:72:5a:21,d0:4f:58:4c:1c:70
signalStrength,-88.333333,-90.5,-88.8,-89.444444,-66.307692,-62.3125,-78.619048,-78.772727,-79.095238,-79.136364,...,-91.0,-90.8,-82.333333,-82.333333,-93.0,-88.333333,-90.727273,-92.0,-89.333333,-90.0

In [392]:



# Create one fingerprint per scan timestamp
wifi_features = ground.pivot_table(
    index="deviceTime",
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)

# Access point not detected = -110 dBm
wifi_features = wifi_features.fillna(-110)

wifi_features = wifi_features.reset_index()
wifi_features['floor'] = 'ground'
wifi_features.to_csv(
    "ground cleaned.csv",
    index=False
)

print(wifi_features.head())
print(wifi_features.shape)

bssid                        deviceTime  00:e6:3a:48:24:80  00:e6:3a:48:24:81  \
0      2026-10-15T11:54:11.158612+05:30             -110.0             -110.0
1      2026-10-15T11:54:20.874275+05:30             -110.0             -110.0
2      2026-10-15T11:54:27.671455+05:30             -110.0             -110.0
3      2026-10-15T11:54:33.373453+05:30             -110.0             -110.0
4       2026-10-15T11:54:40.86848+05:30             -110.0             -110.0

bssid  00:e6:3a:5b:77:40  00:e6:3a:5b:77:41  00:e6:3a:5d:0f:c0  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:5d:0f:c1  00:e6:3a:5d:13:00  00:e6:3a:5d:13:01  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:88:24:80  ...  c0:c7:0a:b2:5a:21  c0:c7:0a:b2:7d:70  \
0                 -110.0  ...             -110.0             -110.0
1                 -110.0  ...             -110.0             -110.0
2                 -110.0  ...             -110.0             -110.0
3                 -110.0  ...             -110.0             -110.0
4                 -110.0  ...             -110.0             -110.0

bssid  c0:c7:0a:b2:7d:71  c0:c7:0a:b3:55:20  c0:c7:0a:b3:55:21  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:4c:1c:70  d0:4f:58:4c:1c:71  d0:4f:58:8c:1c:70  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:8c:1c:71   floor
0                 -110.0  ground
1                 -110.0  ground
2                 -110.0  ground
3                 -110.0  ground
4                 -110.0  ground

[5 rows x 90 columns]
(198, 90)

# first floor

In [393]:
first = pd.read_csv("/content/first floor.csv",comment='#')
first

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1938,2026-10-15T12:11:01.388375+05:30,10.018333,76.342566,-55.4,0.0,22,NS 55035d5186107949 20261015-115404,1939,NaN,NaN,...,149,5745,-62.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,4597.0
1939,2026-10-15T12:11:01.388375+05:30,10.018333,76.342566,-55.4,0.0,22,NS 55035d5186107949 20261015-115404,1940,NaN,NaN,...,132,5660,-82.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,4597.0
1940,2026-10-15T12:11:01.388375+05:30,10.018333,76.342566,-55.4,0.0,22,NS 55035d5186107949 20261015-115404,1941,NaN,NaN,...,64,5320,-64.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,4597.0
1941,2026-10-15T12:11:01.388375+05:30,10.018333,76.342566,-55.4,0.0,22,NS 55035d5186107949 20261015-115404,1942,NaN,NaN,...,11,2462,-64.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,4597.0
1942,2026-10-15T12:11:01.388375+05:30,10.018333,76.342566,-55.4,0.0,22,NS 55035d5186107949 20261015-115404,1943,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211AX,NaN,MHZ_40,55035d5186107949,4597.0

In [394]:
first['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2',
       'Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', nan, 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G'], dtype=object)

In [395]:
['Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G']

['Airtel_KM BAZAAR',
 'OnePlus Nord',
 'Airtel_subi_6149',
 'Y-5',
 'Tranquil_Security',
 'JioAirfiberA6',
 'Airtel_Airtel-Emitra',
 'Galaxy A57 5G 6B36',
 'Airtel_rahu_1651',
 'njn ',
 'GNXS-2.4G-14B850',
 'DESKTOP-OGN1PVD 3341',
 'Airtel_KM BAZAAR_EXT',
 'BIMAL DE INTERIO',
 'Luminar_Lab',
 'H11_Airtel_5G',
 'H11_Airtel_2G',
 'Jio 2nd floor_5G',
 'W3_3929540545',
 'Airtel_sith_1705',
 'Airtel_nith_3450',
 'Luminarkochi_2',
 'Airtel_kevi_7228',
 'realme C65 5G 4A56',
 'Junaid’s iphone',
 'Unavailable',
 'Nikitha Bhaskar',
 'OPPO A5x 5G n5j4',
 'Jio 2nd floor',
 'Rafellia',
 'Airtel_pbdi_7100',
 'EZVIZ_BE4212725',
 'H11_Deco_AP',
 'H11_Deco_AP_Guest',
 '4E6C75-G3010series',
 'Luminar_Ruckus4',
 'GNXS-2.4G-2DF8F0',
 'JioFiber-hIW1G',
 'DIRECT-GDMIJUmsU1',
 'Moto Device',
 'Redmi 13C 5G']

In [396]:
first = first[~first['ssid'].isin(['Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G'])]

In [397]:
first['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2', nan],
      dtype=object)

In [398]:
first = first.dropna(subset='ssid')

In [399]:
first.isna().sum()

deviceTime                   0
latitude                     0
longitude                    0
altitude                     0
speed                        0
accuracy                     0
missionId                    0
recordNumber                 0
sourceAddress             1638
destinationAddress        1638
bssid                        0
beaconInterval            1638
serviceSetType            1638
ssid                         0
supportedRates            1638
extendedSupportedRates    1638
cipherSuites              1638
akmSuites                 1638
encryptionType               0
wps                          0
channel                      0
frequencyMhz                 0
signalStrength               0
snr                       1638
nodeType                  1638
standard                     0
passpoint                 1638
bandwidth                    0
deviceSerialNumber           0
locationAge                  9
dtype: int64

In [400]:



# Create one fingerprint per scan timestamp
wifi_features = first.pivot_table(
    index="deviceTime",
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)

# Access point not detected = -110 dBm
wifi_features = wifi_features.fillna(-110)

wifi_features = wifi_features.reset_index()
wifi_features['floor'] = 'first'
wifi_features.to_csv(
    "first cleaned.csv",
    index=False
)

print(wifi_features.head())
print(wifi_features.shape)

bssid                        deviceTime  00:e6:3a:48:24:80  00:e6:3a:48:24:81  \
0      2026-10-15T11:54:11.158612+05:30             -110.0             -110.0
1      2026-10-15T11:54:20.874275+05:30             -110.0             -110.0
2      2026-10-15T11:54:27.671455+05:30             -110.0             -110.0
3      2026-10-15T11:54:33.373453+05:30             -110.0             -110.0
4       2026-10-15T11:54:40.86848+05:30             -110.0             -110.0

bssid  00:e6:3a:5b:77:40  00:e6:3a:5b:77:41  00:e6:3a:5d:0f:c0  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:5d:0f:c1  00:e6:3a:5d:13:00  00:e6:3a:5d:13:01  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:88:24:80  ...  c0:c7:0a:b2:5a:21  c0:c7:0a:b2:7d:70  \
0                 -110.0  ...             -110.0             -110.0
1                 -110.0  ...             -110.0             -110.0
2                 -110.0  ...             -110.0             -110.0
3                 -110.0  ...             -110.0             -110.0
4                 -110.0  ...             -110.0             -110.0

bssid  c0:c7:0a:b2:7d:71  c0:c7:0a:b3:55:20  c0:c7:0a:b3:55:21  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:4c:1c:70  d0:4f:58:4c:1c:71  d0:4f:58:8c:1c:70  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:8c:1c:71  floor
0                 -110.0  first
1                 -110.0  first
2                 -110.0  first
3                 -110.0  first
4                 -110.0  first

[5 rows x 87 columns]
(83, 87)

# second

In [401]:
second = pd.read_csv("/content/second floor.csv",comment="#")
second

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.00000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3762,2026-10-15T12:15:28.192405+05:30,10.018297,76.34259,-52.5,0.0,54,NS 55035d5186107949 20261015-115404,3763,NaN,NaN,...,11,2462,-61.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,24403.0
3763,2026-10-15T12:15:28.192405+05:30,10.018297,76.34259,-52.5,0.0,54,NS 55035d5186107949 20261015-115404,3764,NaN,NaN,...,64,5320,-79.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,24403.0
3764,2026-10-15T12:15:28.192405+05:30,10.018297,76.34259,-52.5,0.0,54,NS 55035d5186107949 20261015-115404,3765,NaN,NaN,...,1,2412,-64.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,24403.0
3765,2026-10-15T12:15:28.192405+05:30,10.018297,76.34259,-52.5,0.0,54,NS 55035d5186107949 20261015-115404,3766,NaN,NaN,...,64,5320,-80.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,24403.0
3766,2026-10-15T12:15:28.192405+05:30,10.018297,76.34259,-52.5,0.0,54,NS 55035d5186107949 20261015-115404,3767,NaN,NaN,...,11,2462,-60.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,24403.0

In [402]:
second['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2',
       'Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', nan, 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G',
       'Airtel_Sangeeth menon', 'ichc@2018',
       'TATA Intra_CC:B8:5E:D9:0C:4E', 'JioFiber-ZO3g7',
       'DIRECT-DYDESKTOP-1TKQAN2msET', 'GNXS-2.4G-4D4E62', 'iQOO Z9s 5G',
       'ichc@2018_5GHz', 'MeghaazzZ', 'Luminar_C2-2'], dtype=object)

In [403]:
# Filter the 'second' floor DataFrame for SSIDs containing 'luminar'
second = second[second['ssid'].str.contains('luminar', case=False, na=False)]

# Print the unique SSIDs found and preview the filtered data
print("Matching SSIDs:", second['ssid'].unique())
display(second.head())

Matching SSIDs: ['LuminarKochi' 'Luminar_Ruckus' 'Luminar_Lab2' 'Luminar_Lab'
 'Luminarkochi_2' 'Luminar_Ruckus4' 'Luminar_C2-2']

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN

In [404]:



# Create one fingerprint per scan timestamp
wifi_features = second.pivot_table(
    index="deviceTime",
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)

# Access point not detected = -110 dBm
wifi_features = wifi_features.fillna(-110)

wifi_features = wifi_features.reset_index()
wifi_features['floor'] = 'second'
wifi_features.to_csv(
    "second cleaned.csv",
    index=False
)

print(wifi_features.head())
print(wifi_features.shape)

bssid                        deviceTime  00:e6:3a:48:24:80  00:e6:3a:48:24:81  \
0      2026-10-15T11:54:11.158612+05:30             -110.0             -110.0
1      2026-10-15T11:54:20.874275+05:30             -110.0             -110.0
2      2026-10-15T11:54:27.671455+05:30             -110.0             -110.0
3      2026-10-15T11:54:33.373453+05:30             -110.0             -110.0
4       2026-10-15T11:54:40.86848+05:30             -110.0             -110.0

bssid  00:e6:3a:5b:77:40  00:e6:3a:5b:77:41  00:e6:3a:5d:0f:c0  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:5d:0f:c1  00:e6:3a:5d:13:00  00:e6:3a:5d:13:01  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:88:24:80  ...  c0:c7:0a:b2:5a:21  c0:c7:0a:b2:7d:70  \
0                 -110.0  ...             -110.0             -110.0
1                 -110.0  ...             -110.0             -110.0
2                 -110.0  ...             -110.0             -110.0
3                 -110.0  ...             -110.0             -110.0
4                 -110.0  ...             -110.0             -110.0

bssid  c0:c7:0a:b2:7d:71  c0:c7:0a:b3:55:20  c0:c7:0a:b3:55:21  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:4c:1c:70  d0:4f:58:4c:1c:71  d0:4f:58:8c:1c:70  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:8c:1c:71   floor
0                 -110.0  second
1                 -110.0  second
2                 -110.0  second
3                 -110.0  second
4                 -110.0  second

[5 rows x 98 columns]
(117, 98)

# Third

In [405]:
third = pd.read_csv("/content/third floor.csv",comment="#")
third

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.00,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.00,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.00,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.00,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.00,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4108,2026-10-15T12:17:43.01312+05:30,10.018304,76.342601,-49.4,0.44,52,NS 55035d5186107949 20261015-115404,4109,NaN,NaN,...,132,5660,-83.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,8224.0
4109,2026-10-15T12:17:43.01312+05:30,10.018304,76.342601,-49.4,0.44,52,NS 55035d5186107949 20261015-115404,4110,NaN,NaN,...,132,5660,-83.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,8224.0
4110,2026-10-15T12:17:43.01312+05:30,10.018304,76.342601,-49.4,0.44,52,NS 55035d5186107949 20261015-115404,4111,NaN,NaN,...,64,5320,-87.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,8224.0
4111,2026-10-15T12:17:43.01312+05:30,10.018304,76.342601,-49.4,0.44,52,NS 55035d5186107949 20261015-115404,4112,NaN,NaN,...,10,2457,-81.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,8224.0
4112,2026-10-15T12:17:43.01312+05:30,10.018304,76.342601,-49.4,0.44,52,NS 55035d5186107949 20261015-115404,4113,NaN,NaN,...,48,5240,-76.0,NaN,NaN,IEEE80211AX,NaN,MHZ_80,55035d5186107949,8224.0

In [406]:
third['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2',
       'Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', nan, 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G',
       'Airtel_Sangeeth menon', 'ichc@2018',
       'TATA Intra_CC:B8:5E:D9:0C:4E', 'JioFiber-ZO3g7',
       'DIRECT-DYDESKTOP-1TKQAN2msET', 'GNXS-2.4G-4D4E62', 'iQOO Z9s 5G',
       'ichc@2018_5GHz', 'MeghaazzZ', 'Luminar_C2-2', 'home',
       'Realme 8 5G', 'IT Plus', 'Galaxy S25 Ultra DA80', '8D_4g'],
      dtype=object)

In [407]:
# Filter the 'second' floor DataFrame for SSIDs containing 'luminar'
third = third[third['ssid'].str.contains('luminar', case=False, na=False)]

# Print the unique SSIDs found and preview the filtered data
print("Matching SSIDs:", third['ssid'].unique())
display(third.head())

Matching SSIDs: ['LuminarKochi' 'Luminar_Ruckus' 'Luminar_Lab2' 'Luminar_Lab'
 'Luminarkochi_2' 'Luminar_Ruckus4' 'Luminar_C2-2']

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN

In [408]:



# Create one fingerprint per scan timestamp
wifi_features = third.pivot_table(
    index="deviceTime",
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)

# Access point not detected = -110 dBm
wifi_features = wifi_features.fillna(-110)

wifi_features = wifi_features.reset_index()
wifi_features['floor'] = 'third'
wifi_features.to_csv(
    "third cleaned.csv",
    index=False
)

print(wifi_features.head())
print(wifi_features.shape)

bssid                        deviceTime  00:e6:3a:48:24:80  00:e6:3a:48:24:81  \
0      2026-10-15T11:54:11.158612+05:30             -110.0             -110.0
1      2026-10-15T11:54:20.874275+05:30             -110.0             -110.0
2      2026-10-15T11:54:27.671455+05:30             -110.0             -110.0
3      2026-10-15T11:54:33.373453+05:30             -110.0             -110.0
4       2026-10-15T11:54:40.86848+05:30             -110.0             -110.0

bssid  00:e6:3a:5b:77:40  00:e6:3a:5b:77:41  00:e6:3a:5d:0f:c0  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:5d:0f:c1  00:e6:3a:5d:13:00  00:e6:3a:5d:13:01  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:88:24:80  ...  c0:c7:0a:b2:7d:70  c0:c7:0a:b2:7d:71  \
0                 -110.0  ...             -110.0             -110.0
1                 -110.0  ...             -110.0             -110.0
2                 -110.0  ...             -110.0             -110.0
3                 -110.0  ...             -110.0             -110.0
4                 -110.0  ...             -110.0             -110.0

bssid  c0:c7:0a:b2:da:60  c0:c7:0a:b3:55:20  c0:c7:0a:b3:55:21  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:4c:1c:70  d0:4f:58:4c:1c:71  d0:4f:58:8c:1c:70  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:8c:1c:71  floor
0                 -110.0  third
1                 -110.0  third
2                 -110.0  third
3                 -110.0  third
4                 -110.0  third

[5 rows x 101 columns]
(128, 101)

# fourth

In [409]:
fourth = pd.read_csv("/content/fourth floor.csv",comment='#')
fourth

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.000000,0.000000,0.0,0.0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4240,2026-10-15T12:19:28.283117+05:30,10.018299,76.342587,-46.3,0.0,18,NS 55035d5186107949 20261015-115404,4241,NaN,NaN,...,11,2462,-50.0,NaN,NaN,IEEE80211AX,NaN,MHZ_20,55035d5186107949,13496.0
4241,2026-10-15T12:19:28.283117+05:30,10.018299,76.342587,-46.3,0.0,18,NS 55035d5186107949 20261015-115404,4242,NaN,NaN,...,64,5320,-89.0,NaN,NaN,IEEE80211AC,NaN,MHZ_80,55035d5186107949,13496.0
4242,2026-10-15T12:19:28.283117+05:30,10.018299,76.342587,-46.3,0.0,18,NS 55035d5186107949 20261015-115404,4243,NaN,NaN,...,13,2472,-59.0,NaN,NaN,IEEE80211N,NaN,MHZ_40,55035d5186107949,13496.0
4243,2026-10-15T12:19:28.283117+05:30,10.018299,76.342587,-46.3,0.0,18,NS 55035d5186107949 20261015-115404,4244,NaN,NaN,...,44,5220,-53.0,NaN,NaN,IEEE80211AX,NaN,MHZ_80,55035d5186107949,13496.0
4244,2026-10-15T12:19:28.283117+05:30,10.018299,76.342587,-46.3,0.0,18,NS 55035d5186107949 20261015-115404,4245,NaN,NaN,...,48,5240,-37.0,NaN,NaN,IEEE80211AX,NaN,MHZ_80,55035d5186107949,13496.0

In [410]:
fourth['ssid'].unique()

array(['LuminarKochi', 'Luminar_Ruckus', 'Luminar_Lab2',
       'Airtel_KM BAZAAR', 'OnePlus Nord', 'Airtel_subi_6149', nan, 'Y-5',
       'Tranquil_Security', 'JioAirfiberA6', 'Airtel_Airtel-Emitra',
       'Galaxy A57 5G 6B36', 'Airtel_rahu_1651', 'njn ',
       'GNXS-2.4G-14B850', 'DESKTOP-OGN1PVD 3341', 'Airtel_KM BAZAAR_EXT',
       'BIMAL DE INTERIO', 'Luminar_Lab', 'H11_Airtel_5G',
       'H11_Airtel_2G', 'Jio 2nd floor_5G', 'W3_3929540545',
       'Airtel_sith_1705', 'Airtel_nith_3450', 'Luminarkochi_2',
       'Airtel_kevi_7228', 'realme C65 5G 4A56', 'Junaid’s iphone',
       'Unavailable', 'Nikitha Bhaskar', 'OPPO A5x 5G n5j4',
       'Jio 2nd floor', 'Rafellia', 'Airtel_pbdi_7100', 'EZVIZ_BE4212725',
       'H11_Deco_AP', 'H11_Deco_AP_Guest', '4E6C75-G3010series',
       'Luminar_Ruckus4', 'GNXS-2.4G-2DF8F0', 'JioFiber-hIW1G',
       'DIRECT-GDMIJUmsU1', 'Moto Device', 'Redmi 13C 5G',
       'Airtel_Sangeeth menon', 'ichc@2018',
       'TATA Intra_CC:B8:5E:D9:0C:4E', 'JioFiber-ZO3g7',
       'DIRECT-DYDESKTOP-1TKQAN2msET', 'GNXS-2.4G-4D4E62', 'iQOO Z9s 5G',
       'ichc@2018_5GHz', 'MeghaazzZ', 'Luminar_C2-2', 'home',
       'Realme 8 5G', 'IT Plus', 'Galaxy S25 Ultra DA80', '8D_4g',
       'PPC-dd4a', 'OPPO A5 5G y4c9', 'friends hostel gents 1st 5g',
       'friends hostel gents1st 4g'], dtype=object)

In [411]:
# Filter the 'second' floor DataFrame for SSIDs containing 'luminar'
fourth = fourth[fourth['ssid'].str.contains('luminar', case=False, na=False)]

# Print the unique SSIDs found and preview the filtered data
print("Matching SSIDs:", fourth['ssid'].unique())
display(fourth.head())

Matching SSIDs: ['LuminarKochi' 'Luminar_Ruckus' 'Luminar_Lab2' 'Luminar_Lab'
 'Luminarkochi_2' 'Luminar_Ruckus4' 'Luminar_C2-2']

,deviceTime,latitude,longitude,altitude,speed,accuracy,missionId,recordNumber,sourceAddress,destinationAddress,...,channel,frequencyMhz,signalStrength,snr,nodeType,standard,passpoint,bandwidth,deviceSerialNumber,locationAge
0,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,1,NaN,NaN,...,6,2437,-91.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
1,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,2,NaN,NaN,...,6,2437,-88.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
2,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,3,NaN,NaN,...,6,2437,-89.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
3,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,4,NaN,NaN,...,6,2437,-76.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN
4,2026-10-15T11:54:11.158612+05:30,0.0,0.0,0.0,0.0,0,NS 55035d5186107949 20261015-115404,5,NaN,NaN,...,6,2437,-83.0,NaN,NaN,IEEE80211N,NaN,MHZ_20,55035d5186107949,NaN

In [412]:



# Create one fingerprint per scan timestamp
wifi_features = fourth.pivot_table(
    index="deviceTime",
    columns="bssid",
    values="signalStrength",
    aggfunc="mean"
)

# Access point not detected = -110 dBm
wifi_features = wifi_features.fillna(-110)

wifi_features = wifi_features.reset_index()
wifi_features['floor'] = 'fourth'
wifi_features.to_csv(
    "fourth cleaned.csv",
    index=False
)

print(wifi_features.head())
print(wifi_features.shape)

bssid                        deviceTime  00:e6:3a:48:24:80  00:e6:3a:48:24:81  \
0      2026-10-15T11:54:11.158612+05:30             -110.0             -110.0
1      2026-10-15T11:54:20.874275+05:30             -110.0             -110.0
2      2026-10-15T11:54:27.671455+05:30             -110.0             -110.0
3      2026-10-15T11:54:33.373453+05:30             -110.0             -110.0
4       2026-10-15T11:54:40.86848+05:30             -110.0             -110.0

bssid  00:e6:3a:5b:77:40  00:e6:3a:5b:77:41  00:e6:3a:5d:0f:c0  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:5d:0f:c1  00:e6:3a:5d:13:00  00:e6:3a:5d:13:01  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  00:e6:3a:88:24:80  ...  c0:c7:0a:b2:7d:70  c0:c7:0a:b2:7d:71  \
0                 -110.0  ...             -110.0             -110.0
1                 -110.0  ...             -110.0             -110.0
2                 -110.0  ...             -110.0             -110.0
3                 -110.0  ...             -110.0             -110.0
4                 -110.0  ...             -110.0             -110.0

bssid  c0:c7:0a:b2:da:60  c0:c7:0a:b3:55:20  c0:c7:0a:b3:55:21  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:4c:1c:70  d0:4f:58:4c:1c:71  d0:4f:58:8c:1c:70  \
0                 -110.0             -110.0             -110.0
1                 -110.0             -110.0             -110.0
2                 -110.0             -110.0             -110.0
3                 -110.0             -110.0             -110.0
4                 -110.0             -110.0             -110.0

bssid  d0:4f:58:8c:1c:71   floor
0                 -110.0  fourth
1                 -110.0  fourth
2                 -110.0  fourth
3                 -110.0  fourth
4                 -110.0  fourth

[5 rows x 102 columns]
(138, 102)