## **Handling Missing Values**

In [ ]:
import pandas as pd
from numpy._core.fromnumeric import mean

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/files/missing_data.csv')

In [ ]:
df.shape

(32, 5)

In [ ]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [ ]:
df.isna().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

# fill missing values

In [ ]:
#df.fillna(300,inplace=True)

In [ ]:
#df

# fill calories missing values

In [ ]:
#
# df['Calories'].fillna(mean(df['Calories']),inplace=True)

# fill date coloumns

In [ ]:
# df['Date'].fillna('2020-12-12',inplace=True)

In [ ]:
# df

#mean median mode for handling missing values in a coloumn

In [ ]:
# df['Calories'].unique()

In [ ]:
# df['Calories'].fillna(df['Calories'].mean(),inplace=True)
# df

In [ ]:
# x=df['Date'].mode()[0]
# df.fillna(x,inplace=True)
# df

## dropna() --delete missing values

In [ ]:
# df.dropna(inplace=True,ignore_index=True)
# df

delete specific row

In [ ]:
df.dropna(subset=['Date'],inplace=True,ignore_index=True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        60  '2020/12/23'    130       101     300.0
23        45  '2020/12/24'    105       132     246.0
24        60  '2020/12/25'    102       126     334.5
25        60      20201226    100       120     250.0
26        60  '2020/12/27'     92       118     241.0
27        60  '2020/12/28'    103       132       NaN
28        60  '2020/12/29'    100       132     280.0
29        60  '2020/12/30'    102       129     380.3
30        60  '2020/12/31'     92       115     243.0

## handling wrong data

In [ ]:
y=df['Calories'].mode()[0]
for i in df.index:
  if df.loc[i,'Calories']>y:
    df.loc[i,'Calories']=y

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     300.0
1         60  '2020/12/02'    117       145     300.0
2         60  '2020/12/03'    103       135     300.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     300.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     300.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     300.0
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     300.0
14        60  '2020/12/14'    104       132     300.0
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     300.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     300.0
22        60  '2020/12/23'    130       101     300.0
23        45  '2020/12/24'    105       132     246.0
24        60  '2020/12/25'    102       126     300.0
25        60      20201226    100       120     250.0
26        60  '2020/12/27'     92       118     241.0
27        60  '2020/12/28'    103       132       NaN
28        60  '2020/12/29'    100       132     280.0
29        60  '2020/12/30'    102       129     300.0
30        60  '2020/12/31'     92       115     243.0

## wrong format

In [ ]:
df['Date']=df['Date'].replace('20201223','2020/12/26')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        60  '2020/12/23'    130       101     300.0
23        45  '2020/12/24'    105       132     246.0
24        60  '2020/12/25'    102       126     334.5
25        60      20201226    100       120     250.0
26        60  '2020/12/27'     92       118     241.0
27        60  '2020/12/28'    103       132       NaN
28        60  '2020/12/29'    100       132     280.0
29        60  '2020/12/30'    102       129     380.3
30        60  '2020/12/31'     92       115     243.0

In [ ]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object