In [4]:
import pandas as pd

df=pd.read_csv(r'C:\Desktop\luminar\Eda1\pandas1\files\customer1.csv')

print(df)

          id     fname    lname  age                        prof      loc
0    4000001  Kristina    Chung   55                       Pilot    india
1    4000002     Paige     Chen   74                     Teacher       uk
2    4000003    Sherri   Melton   34                 Firefighter       us
3    4000004  Gretchen     Hill   66  Computer hardware engineer    china
4    4000005     Karen  Puckett   74                      Lawyer   africa
..       ...       ...      ...  ...                         ...      ...
458  4000459  Gretchen  Francis   60                  Politician  ireland
459  4000460    Cheryl     Horn   40                Veterinarian  ireland
460  4000461    Audrey  Forrest   50                   Architect  ireland
461  4000462      Alan    Levin   43                Statistician  ireland
462  4000463     Wayne   Weiner   70                       Actor  ireland

[463 rows x 6 columns]

In [5]:
# #age above 50 f,l,age,prof

df[df['age']>50][['fname','lname','age','prof']]

        fname    lname  age                        prof
0    Kristina    Chung   55                       Pilot
1       Paige     Chen   74                     Teacher
3    Gretchen     Hill   66  Computer hardware engineer
4       Karen  Puckett   74                      Lawyer
7       Hazel   Bender   63                   Carpenter
..        ...      ...  ...                         ...
446    Jordan   Knight   65                 Electrician
452       Kim  Hensley   64                Photographer
454   Deborah   French   56                  Accountant
458  Gretchen  Francis   60                  Politician
462     Wayne   Weiner   70                       Actor

[235 rows x 4 columns]

In [7]:
# age below 40 f,l,age

df[df['age']<40][['fname','lname','age']]

        fname   lname  age
2      Sherri  Melton   34
8     Malcolm  Wagner   39
11      Sandy  Raynor   26
20       Alex     May   39
23   Franklin    Vick   28
..        ...     ...  ...
450   Russell    Hess   21
451    Marsha    Gold   36
453  Virginia  Turner   22
455     Peter  Hughes   38
456   Bernard    Pate   34

[150 rows x 3 columns]

## india work f,l,age

In [8]:
df[df['loc']=='india'][['fname','lname','age']]

       fname       lname  age
0   Kristina       Chung   55
7      Hazel      Bender   63
8    Malcolm      Wagner   39
9    Dolores  McLaughlin   60
10   Francis    McNamara   47
11     Sandy      Raynor   26
12    Marion        Moon   41
13      Beth     Woodard   65
14     Julia       Desai   49
15    Jerome     Wallace   52
16      Neal    Lawrence   72
17      Jean     Griffin   45
18  Kristine   Dougherty   63
19   Crystal      Powers   67
20      Alex         May   39
21      Eric      Steele   66
22    Wesley      Teague   42
23  Franklin        Vick   28
24    Claire   Gallagher   42
25    Marian     Solomon   27
26    Marcia       Walsh   64

# india work and doctor pro

In [12]:
df[(df['loc']=='india') & (df['prof']=='Doctor')][['fname','lname','age']]

   fname   lname  age
21  Eric  Steele   66


# pilot prof f,l,age

In [11]:
df[df['prof']=='Pilot'][['fname','lname','age']]

         fname     lname  age
0     Kristina     Chung   55
6        Elsie  Hamilton   43
228       Faye    Norman   64
229      Kathy     Burch   28
250     Jeremy     House   61
270      Alice     Nance   59
321  Geraldine    Jensen   50
335     Steven   Ballard   62
391       Emma     Olson   74
402        Leo  Lassiter   65
422       Alan    O'Neal   59
424       Dean      Lutz   26
439     Hannah  Langston   25